<?php

/**
 * One-off generator for app/Enums/Nationality.php.
 *
 * Reads German country labels from umpirsky/country-list (ISO 3166-1 alpha-2)
 * and emits a backed string enum implementing LabeledEnum.
 *
 * Re-run only when ISO publishes a change:
 *   php scripts/generate-nationality-enum.php
 */

require __DIR__.'/../vendor/autoload.php';

$source = __DIR__.'/../vendor/umpirsky/country-list/data/de/country.php';

if (! is_file($source)) {
	fwrite(STDERR, "Source file not found: {$source}\n");
	exit(1);
}

/** @var array<string, string> $countries */
$countries = require $source;

ksort($countries);

$caseName = static function (string $code): string {
	return preg_match('/^[A-Z]/', $code[0]) ? $code : 'C'.$code;
};

$casesPhp = [];
$labelsPhp = [];
$ordersPhp = [];
$order = 1;
foreach ($countries as $code => $label) {
	$code = strtoupper(trim($code));
	if (! preg_match('/^[A-Z]{2}$/', $code)) {
		continue;
	}
	$label = addslashes($label);
	$casesPhp[] = "    case {$code} = '{$code}';";
	$labelsPhp[] = "            self::{$code} => '{$label}',";
	$ordersPhp[] = "            self::{$code} => {$order},";
	$order++;
}

$cases = implode("\n", $casesPhp);
$labels = implode("\n", $labelsPhp);
$orders = implode("\n", $ordersPhp);

$contents = <<<PHP
<?php

namespace App\\Enums;

/**
 * ISO 3166-1 alpha-2 country codes with German labels.
 *
 * Generated by scripts/generate-nationality-enum.php — do not edit by hand.
 */
enum Nationality: string implements LabeledEnum
{
{$cases}

	public function label(): string
	{
		return match (\$this) {
{$labels}
		};
	}

	public function sortOrder(): int
	{
		return match (\$this) {
{$orders}
		};
	}

	public function active(): bool
	{
		return true;
	}
}
PHP;

$target = __DIR__.'/../app/Enums/Nationality.php';
file_put_contents($target, $contents."\n");

echo "Generated ".count($casesPhp)." cases into {$target}\n";
