<?php

namespace App\Enums;

/**
 * ISO 3166-1 alpha-2 country codes with German labels. Maintained by hand.
 */
enum Nationality: string implements LabeledEnum
{
	case AD = 'AD';
	case AE = 'AE';
	case AF = 'AF';
	case AG = 'AG';
	case AI = 'AI';
	case AL = 'AL';
	case AM = 'AM';
	case AO = 'AO';
	case AQ = 'AQ';
	case AR = 'AR';
	case AS = 'AS';
	case AT = 'AT';
	case AU = 'AU';
	case AW = 'AW';
	case AX = 'AX';
	case AZ = 'AZ';
	case BA = 'BA';
	case BB = 'BB';
	case BD = 'BD';
	case BE = 'BE';
	case BF = 'BF';
	case BG = 'BG';
	case BH = 'BH';
	case BI = 'BI';
	case BJ = 'BJ';
	case BL = 'BL';
	case BM = 'BM';
	case BN = 'BN';
	case BO = 'BO';
	case BQ = 'BQ';
	case BR = 'BR';
	case BS = 'BS';
	case BT = 'BT';
	case BV = 'BV';
	case BW = 'BW';
	case BY = 'BY';
	case BZ = 'BZ';
	case CA = 'CA';
	case CC = 'CC';
	case CD = 'CD';
	case CF = 'CF';
	case CG = 'CG';
	case CH = 'CH';
	case CI = 'CI';
	case CK = 'CK';
	case CL = 'CL';
	case CM = 'CM';
	case CN = 'CN';
	case CO = 'CO';
	case CR = 'CR';
	case CU = 'CU';
	case CV = 'CV';
	case CW = 'CW';
	case CX = 'CX';
	case CY = 'CY';
	case CZ = 'CZ';
	case DE = 'DE';
	case DJ = 'DJ';
	case DK = 'DK';
	case DM = 'DM';
	case DO = 'DO';
	case DZ = 'DZ';
	case EC = 'EC';
	case EE = 'EE';
	case EG = 'EG';
	case EH = 'EH';
	case ER = 'ER';
	case ES = 'ES';
	case ET = 'ET';
	case FI = 'FI';
	case FJ = 'FJ';
	case FK = 'FK';
	case FM = 'FM';
	case FO = 'FO';
	case FR = 'FR';
	case GA = 'GA';
	case GB = 'GB';
	case GD = 'GD';
	case GE = 'GE';
	case GF = 'GF';
	case GG = 'GG';
	case GH = 'GH';
	case GI = 'GI';
	case GL = 'GL';
	case GM = 'GM';
	case GN = 'GN';
	case GP = 'GP';
	case GQ = 'GQ';
	case GR = 'GR';
	case GS = 'GS';
	case GT = 'GT';
	case GU = 'GU';
	case GW = 'GW';
	case GY = 'GY';
	case HK = 'HK';
	case HM = 'HM';
	case HN = 'HN';
	case HR = 'HR';
	case HT = 'HT';
	case HU = 'HU';
	case ID = 'ID';
	case IE = 'IE';
	case IL = 'IL';
	case IM = 'IM';
	case IN = 'IN';
	case IO = 'IO';
	case IQ = 'IQ';
	case IR = 'IR';
	case IS = 'IS';
	case IT = 'IT';
	case JE = 'JE';
	case JM = 'JM';
	case JO = 'JO';
	case JP = 'JP';
	case KE = 'KE';
	case KG = 'KG';
	case KH = 'KH';
	case KI = 'KI';
	case KM = 'KM';
	case KN = 'KN';
	case KP = 'KP';
	case KR = 'KR';
	case KW = 'KW';
	case KY = 'KY';
	case KZ = 'KZ';
	case LA = 'LA';
	case LB = 'LB';
	case LC = 'LC';
	case LI = 'LI';
	case LK = 'LK';
	case LR = 'LR';
	case LS = 'LS';
	case LT = 'LT';
	case LU = 'LU';
	case LV = 'LV';
	case LY = 'LY';
	case MA = 'MA';
	case MC = 'MC';
	case MD = 'MD';
	case ME = 'ME';
	case MF = 'MF';
	case MG = 'MG';
	case MH = 'MH';
	case MK = 'MK';
	case ML = 'ML';
	case MM = 'MM';
	case MN = 'MN';
	case MO = 'MO';
	case MP = 'MP';
	case MQ = 'MQ';
	case MR = 'MR';
	case MS = 'MS';
	case MT = 'MT';
	case MU = 'MU';
	case MV = 'MV';
	case MW = 'MW';
	case MX = 'MX';
	case MY = 'MY';
	case MZ = 'MZ';
	case NA = 'NA';
	case NC = 'NC';
	case NE = 'NE';
	case NF = 'NF';
	case NG = 'NG';
	case NI = 'NI';
	case NL = 'NL';
	case NO = 'NO';
	case NP = 'NP';
	case NR = 'NR';
	case NU = 'NU';
	case NZ = 'NZ';
	case OM = 'OM';
	case PA = 'PA';
	case PE = 'PE';
	case PF = 'PF';
	case PG = 'PG';
	case PH = 'PH';
	case PK = 'PK';
	case PL = 'PL';
	case PM = 'PM';
	case PN = 'PN';
	case PR = 'PR';
	case PS = 'PS';
	case PT = 'PT';
	case PW = 'PW';
	case PY = 'PY';
	case QA = 'QA';
	case RE = 'RE';
	case RO = 'RO';
	case RS = 'RS';
	case RU = 'RU';
	case RW = 'RW';
	case SA = 'SA';
	case SB = 'SB';
	case SC = 'SC';
	case SD = 'SD';
	case SE = 'SE';
	case SG = 'SG';
	case SH = 'SH';
	case SI = 'SI';
	case SJ = 'SJ';
	case SK = 'SK';
	case SL = 'SL';
	case SM = 'SM';
	case SN = 'SN';
	case SO = 'SO';
	case SR = 'SR';
	case SS = 'SS';
	case ST = 'ST';
	case SV = 'SV';
	case SX = 'SX';
	case SY = 'SY';
	case SZ = 'SZ';
	case TC = 'TC';
	case TD = 'TD';
	case TF = 'TF';
	case TG = 'TG';
	case TH = 'TH';
	case TJ = 'TJ';
	case TK = 'TK';
	case TL = 'TL';
	case TM = 'TM';
	case TN = 'TN';
	case TO = 'TO';
	case TR = 'TR';
	case TT = 'TT';
	case TV = 'TV';
	case TW = 'TW';
	case TZ = 'TZ';
	case UA = 'UA';
	case UG = 'UG';
	case UM = 'UM';
	case US = 'US';
	case UY = 'UY';
	case UZ = 'UZ';
	case VA = 'VA';
	case VC = 'VC';
	case VE = 'VE';
	case VG = 'VG';
	case VI = 'VI';
	case VN = 'VN';
	case VU = 'VU';
	case WF = 'WF';
	case WS = 'WS';
	case YE = 'YE';
	case YT = 'YT';
	case ZA = 'ZA';
	case ZM = 'ZM';
	case ZW = 'ZW';

	public function label(): string
	{
		return match ($this) {
			self::AD => 'Andorra',
			self::AE => 'Vereinigte Arabische Emirate',
			self::AF => 'Afghanistan',
			self::AG => 'Antigua und Barbuda',
			self::AI => 'Anguilla',
			self::AL => 'Albanien',
			self::AM => 'Armenien',
			self::AO => 'Angola',
			self::AQ => 'Antarktis',
			self::AR => 'Argentinien',
			self::AS => 'Amerikanisch-Samoa',
			self::AT => 'Österreich',
			self::AU => 'Australien',
			self::AW => 'Aruba',
			self::AX => 'Ålandinseln',
			self::AZ => 'Aserbaidschan',
			self::BA => 'Bosnien und Herzegowina',
			self::BB => 'Barbados',
			self::BD => 'Bangladesch',
			self::BE => 'Belgien',
			self::BF => 'Burkina Faso',
			self::BG => 'Bulgarien',
			self::BH => 'Bahrain',
			self::BI => 'Burundi',
			self::BJ => 'Benin',
			self::BL => 'St. Barthélemy',
			self::BM => 'Bermuda',
			self::BN => 'Brunei Darussalam',
			self::BO => 'Bolivien',
			self::BQ => 'Bonaire, Sint Eustatius und Saba',
			self::BR => 'Brasilien',
			self::BS => 'Bahamas',
			self::BT => 'Bhutan',
			self::BV => 'Bouvetinsel',
			self::BW => 'Botsuana',
			self::BY => 'Belarus',
			self::BZ => 'Belize',
			self::CA => 'Kanada',
			self::CC => 'Kokosinseln',
			self::CD => 'Kongo-Kinshasa',
			self::CF => 'Zentralafrikanische Republik',
			self::CG => 'Kongo-Brazzaville',
			self::CH => 'Schweiz',
			self::CI => 'Côte d’Ivoire',
			self::CK => 'Cookinseln',
			self::CL => 'Chile',
			self::CM => 'Kamerun',
			self::CN => 'China',
			self::CO => 'Kolumbien',
			self::CR => 'Costa Rica',
			self::CU => 'Kuba',
			self::CV => 'Cabo Verde',
			self::CW => 'Curaçao',
			self::CX => 'Weihnachtsinsel',
			self::CY => 'Zypern',
			self::CZ => 'Tschechien',
			self::DE => 'Deutschland',
			self::DJ => 'Dschibuti',
			self::DK => 'Dänemark',
			self::DM => 'Dominica',
			self::DO => 'Dominikanische Republik',
			self::DZ => 'Algerien',
			self::EC => 'Ecuador',
			self::EE => 'Estland',
			self::EG => 'Ägypten',
			self::EH => 'Westsahara',
			self::ER => 'Eritrea',
			self::ES => 'Spanien',
			self::ET => 'Äthiopien',
			self::FI => 'Finnland',
			self::FJ => 'Fidschi',
			self::FK => 'Falklandinseln',
			self::FM => 'Mikronesien',
			self::FO => 'Färöer',
			self::FR => 'Frankreich',
			self::GA => 'Gabun',
			self::GB => 'Vereinigtes Königreich',
			self::GD => 'Grenada',
			self::GE => 'Georgien',
			self::GF => 'Französisch-Guayana',
			self::GG => 'Guernsey',
			self::GH => 'Ghana',
			self::GI => 'Gibraltar',
			self::GL => 'Grönland',
			self::GM => 'Gambia',
			self::GN => 'Guinea',
			self::GP => 'Guadeloupe',
			self::GQ => 'Äquatorialguinea',
			self::GR => 'Griechenland',
			self::GS => 'Südgeorgien und die Südlichen Sandwichinseln',
			self::GT => 'Guatemala',
			self::GU => 'Guam',
			self::GW => 'Guinea-Bissau',
			self::GY => 'Guyana',
			self::HK => 'Sonderverwaltungsregion Hongkong',
			self::HM => 'Heard und McDonaldinseln',
			self::HN => 'Honduras',
			self::HR => 'Kroatien',
			self::HT => 'Haiti',
			self::HU => 'Ungarn',
			self::ID => 'Indonesien',
			self::IE => 'Irland',
			self::IL => 'Israel',
			self::IM => 'Isle of Man',
			self::IN => 'Indien',
			self::IO => 'Britisches Territorium im Indischen Ozean',
			self::IQ => 'Irak',
			self::IR => 'Iran',
			self::IS => 'Island',
			self::IT => 'Italien',
			self::JE => 'Jersey',
			self::JM => 'Jamaika',
			self::JO => 'Jordanien',
			self::JP => 'Japan',
			self::KE => 'Kenia',
			self::KG => 'Kirgisistan',
			self::KH => 'Kambodscha',
			self::KI => 'Kiribati',
			self::KM => 'Komoren',
			self::KN => 'St. Kitts und Nevis',
			self::KP => 'Nordkorea',
			self::KR => 'Südkorea',
			self::KW => 'Kuwait',
			self::KY => 'Kaimaninseln',
			self::KZ => 'Kasachstan',
			self::LA => 'Laos',
			self::LB => 'Libanon',
			self::LC => 'St. Lucia',
			self::LI => 'Liechtenstein',
			self::LK => 'Sri Lanka',
			self::LR => 'Liberia',
			self::LS => 'Lesotho',
			self::LT => 'Litauen',
			self::LU => 'Luxemburg',
			self::LV => 'Lettland',
			self::LY => 'Libyen',
			self::MA => 'Marokko',
			self::MC => 'Monaco',
			self::MD => 'Republik Moldau',
			self::ME => 'Montenegro',
			self::MF => 'St. Martin',
			self::MG => 'Madagaskar',
			self::MH => 'Marshallinseln',
			self::MK => 'Nordmazedonien',
			self::ML => 'Mali',
			self::MM => 'Myanmar',
			self::MN => 'Mongolei',
			self::MO => 'Sonderverwaltungsregion Macau',
			self::MP => 'Nördliche Marianen',
			self::MQ => 'Martinique',
			self::MR => 'Mauretanien',
			self::MS => 'Montserrat',
			self::MT => 'Malta',
			self::MU => 'Mauritius',
			self::MV => 'Malediven',
			self::MW => 'Malawi',
			self::MX => 'Mexiko',
			self::MY => 'Malaysia',
			self::MZ => 'Mosambik',
			self::NA => 'Namibia',
			self::NC => 'Neukaledonien',
			self::NE => 'Niger',
			self::NF => 'Norfolkinsel',
			self::NG => 'Nigeria',
			self::NI => 'Nicaragua',
			self::NL => 'Niederlande',
			self::NO => 'Norwegen',
			self::NP => 'Nepal',
			self::NR => 'Nauru',
			self::NU => 'Niue',
			self::NZ => 'Neuseeland',
			self::OM => 'Oman',
			self::PA => 'Panama',
			self::PE => 'Peru',
			self::PF => 'Französisch-Polynesien',
			self::PG => 'Papua-Neuguinea',
			self::PH => 'Philippinen',
			self::PK => 'Pakistan',
			self::PL => 'Polen',
			self::PM => 'St. Pierre und Miquelon',
			self::PN => 'Pitcairninseln',
			self::PR => 'Puerto Rico',
			self::PS => 'Palästinensische Autonomiegebiete',
			self::PT => 'Portugal',
			self::PW => 'Palau',
			self::PY => 'Paraguay',
			self::QA => 'Katar',
			self::RE => 'Réunion',
			self::RO => 'Rumänien',
			self::RS => 'Serbien',
			self::RU => 'Russland',
			self::RW => 'Ruanda',
			self::SA => 'Saudi-Arabien',
			self::SB => 'Salomonen',
			self::SC => 'Seychellen',
			self::SD => 'Sudan',
			self::SE => 'Schweden',
			self::SG => 'Singapur',
			self::SH => 'St. Helena',
			self::SI => 'Slowenien',
			self::SJ => 'Spitzbergen und Jan Mayen',
			self::SK => 'Slowakei',
			self::SL => 'Sierra Leone',
			self::SM => 'San Marino',
			self::SN => 'Senegal',
			self::SO => 'Somalia',
			self::SR => 'Suriname',
			self::SS => 'Südsudan',
			self::ST => 'São Tomé und Príncipe',
			self::SV => 'El Salvador',
			self::SX => 'Sint Maarten',
			self::SY => 'Syrien',
			self::SZ => 'Eswatini',
			self::TC => 'Turks- und Caicosinseln',
			self::TD => 'Tschad',
			self::TF => 'Französische Süd- und Antarktisgebiete',
			self::TG => 'Togo',
			self::TH => 'Thailand',
			self::TJ => 'Tadschikistan',
			self::TK => 'Tokelau',
			self::TL => 'Timor-Leste',
			self::TM => 'Turkmenistan',
			self::TN => 'Tunesien',
			self::TO => 'Tonga',
			self::TR => 'Türkei',
			self::TT => 'Trinidad und Tobago',
			self::TV => 'Tuvalu',
			self::TW => 'Taiwan',
			self::TZ => 'Tansania',
			self::UA => 'Ukraine',
			self::UG => 'Uganda',
			self::UM => 'Amerikanische Überseeinseln',
			self::US => 'Vereinigte Staaten',
			self::UY => 'Uruguay',
			self::UZ => 'Usbekistan',
			self::VA => 'Vatikanstadt',
			self::VC => 'St. Vincent und die Grenadinen',
			self::VE => 'Venezuela',
			self::VG => 'Britische Jungferninseln',
			self::VI => 'Amerikanische Jungferninseln',
			self::VN => 'Vietnam',
			self::VU => 'Vanuatu',
			self::WF => 'Wallis und Futuna',
			self::WS => 'Samoa',
			self::YE => 'Jemen',
			self::YT => 'Mayotte',
			self::ZA => 'Südafrika',
			self::ZM => 'Sambia',
			self::ZW => 'Simbabwe',
		};
	}

	public function sortOrder(): int
	{
		// German alphabetical order, with surrounding countries pinned to the
		// top (Schweiz, Deutschland, Frankreich, Österreich, Italien).
		return match ($this) {
			self::CH => 1, // Schweiz
			self::DE => 2, // Deutschland
			self::FR => 3, // Frankreich
			self::AT => 4, // Österreich
			self::IT => 5, // Italien
			self::AF => 6, // Afghanistan
			self::EG => 7, // Ägypten
			self::AX => 8, // Ålandinseln
			self::AL => 9, // Albanien
			self::DZ => 10, // Algerien
			self::AS => 11, // Amerikanisch-Samoa
			self::VI => 12, // Amerikanische Jungferninseln
			self::UM => 13, // Amerikanische Überseeinseln
			self::AD => 14, // Andorra
			self::AO => 15, // Angola
			self::AI => 16, // Anguilla
			self::AQ => 17, // Antarktis
			self::AG => 18, // Antigua und Barbuda
			self::GQ => 19, // Äquatorialguinea
			self::AR => 20, // Argentinien
			self::AM => 21, // Armenien
			self::AW => 22, // Aruba
			self::AZ => 23, // Aserbaidschan
			self::ET => 24, // Äthiopien
			self::AU => 25, // Australien
			self::BS => 26, // Bahamas
			self::BH => 27, // Bahrain
			self::BD => 28, // Bangladesch
			self::BB => 29, // Barbados
			self::BY => 30, // Belarus
			self::BE => 31, // Belgien
			self::BZ => 32, // Belize
			self::BJ => 33, // Benin
			self::BM => 34, // Bermuda
			self::BT => 35, // Bhutan
			self::BO => 36, // Bolivien
			self::BQ => 37, // Bonaire, Sint Eustatius und Saba
			self::BA => 38, // Bosnien und Herzegowina
			self::BW => 39, // Botsuana
			self::BV => 40, // Bouvetinsel
			self::BR => 41, // Brasilien
			self::VG => 42, // Britische Jungferninseln
			self::IO => 43, // Britisches Territorium im Indischen Ozean
			self::BN => 44, // Brunei Darussalam
			self::BG => 45, // Bulgarien
			self::BF => 46, // Burkina Faso
			self::BI => 47, // Burundi
			self::CV => 48, // Cabo Verde
			self::CL => 49, // Chile
			self::CN => 50, // China
			self::CK => 51, // Cookinseln
			self::CR => 52, // Costa Rica
			self::CI => 53, // Côte d’Ivoire
			self::CW => 54, // Curaçao
			self::DK => 55, // Dänemark
			self::DM => 56, // Dominica
			self::DO => 57, // Dominikanische Republik
			self::DJ => 58, // Dschibuti
			self::EC => 59, // Ecuador
			self::SV => 60, // El Salvador
			self::ER => 61, // Eritrea
			self::EE => 62, // Estland
			self::SZ => 63, // Eswatini
			self::FK => 64, // Falklandinseln
			self::FO => 65, // Färöer
			self::FJ => 66, // Fidschi
			self::FI => 67, // Finnland
			self::GF => 68, // Französisch-Guayana
			self::PF => 69, // Französisch-Polynesien
			self::TF => 70, // Französische Süd- und Antarktisgebiete
			self::GA => 71, // Gabun
			self::GM => 72, // Gambia
			self::GE => 73, // Georgien
			self::GH => 74, // Ghana
			self::GI => 75, // Gibraltar
			self::GD => 76, // Grenada
			self::GR => 77, // Griechenland
			self::GL => 78, // Grönland
			self::GP => 79, // Guadeloupe
			self::GU => 80, // Guam
			self::GT => 81, // Guatemala
			self::GG => 82, // Guernsey
			self::GN => 83, // Guinea
			self::GW => 84, // Guinea-Bissau
			self::GY => 85, // Guyana
			self::HT => 86, // Haiti
			self::HM => 87, // Heard und McDonaldinseln
			self::HN => 88, // Honduras
			self::IN => 89, // Indien
			self::ID => 90, // Indonesien
			self::IQ => 91, // Irak
			self::IR => 92, // Iran
			self::IE => 93, // Irland
			self::IS => 94, // Island
			self::IM => 95, // Isle of Man
			self::IL => 96, // Israel
			self::JM => 97, // Jamaika
			self::JP => 98, // Japan
			self::YE => 99, // Jemen
			self::JE => 100, // Jersey
			self::JO => 101, // Jordanien
			self::KY => 102, // Kaimaninseln
			self::KH => 103, // Kambodscha
			self::CM => 104, // Kamerun
			self::CA => 105, // Kanada
			self::KZ => 106, // Kasachstan
			self::QA => 107, // Katar
			self::KE => 108, // Kenia
			self::KG => 109, // Kirgisistan
			self::KI => 110, // Kiribati
			self::CC => 111, // Kokosinseln
			self::CO => 112, // Kolumbien
			self::KM => 113, // Komoren
			self::CG => 114, // Kongo-Brazzaville
			self::CD => 115, // Kongo-Kinshasa
			self::HR => 116, // Kroatien
			self::CU => 117, // Kuba
			self::KW => 118, // Kuwait
			self::LA => 119, // Laos
			self::LS => 120, // Lesotho
			self::LV => 121, // Lettland
			self::LB => 122, // Libanon
			self::LR => 123, // Liberia
			self::LY => 124, // Libyen
			self::LI => 125, // Liechtenstein
			self::LT => 126, // Litauen
			self::LU => 127, // Luxemburg
			self::MG => 128, // Madagaskar
			self::MW => 129, // Malawi
			self::MY => 130, // Malaysia
			self::MV => 131, // Malediven
			self::ML => 132, // Mali
			self::MT => 133, // Malta
			self::MA => 134, // Marokko
			self::MH => 135, // Marshallinseln
			self::MQ => 136, // Martinique
			self::MR => 137, // Mauretanien
			self::MU => 138, // Mauritius
			self::YT => 139, // Mayotte
			self::MX => 140, // Mexiko
			self::FM => 141, // Mikronesien
			self::MC => 142, // Monaco
			self::MN => 143, // Mongolei
			self::ME => 144, // Montenegro
			self::MS => 145, // Montserrat
			self::MZ => 146, // Mosambik
			self::MM => 147, // Myanmar
			self::NA => 148, // Namibia
			self::NR => 149, // Nauru
			self::NP => 150, // Nepal
			self::NC => 151, // Neukaledonien
			self::NZ => 152, // Neuseeland
			self::NI => 153, // Nicaragua
			self::NL => 154, // Niederlande
			self::NE => 155, // Niger
			self::NG => 156, // Nigeria
			self::NU => 157, // Niue
			self::KP => 158, // Nordkorea
			self::MP => 159, // Nördliche Marianen
			self::MK => 160, // Nordmazedonien
			self::NF => 161, // Norfolkinsel
			self::NO => 162, // Norwegen
			self::OM => 163, // Oman
			self::PK => 164, // Pakistan
			self::PS => 165, // Palästinensische Autonomiegebiete
			self::PW => 166, // Palau
			self::PA => 167, // Panama
			self::PG => 168, // Papua-Neuguinea
			self::PY => 169, // Paraguay
			self::PE => 170, // Peru
			self::PH => 171, // Philippinen
			self::PN => 172, // Pitcairninseln
			self::PL => 173, // Polen
			self::PT => 174, // Portugal
			self::PR => 175, // Puerto Rico
			self::MD => 176, // Republik Moldau
			self::RE => 177, // Réunion
			self::RW => 178, // Ruanda
			self::RO => 179, // Rumänien
			self::RU => 180, // Russland
			self::SB => 181, // Salomonen
			self::ZM => 182, // Sambia
			self::WS => 183, // Samoa
			self::SM => 184, // San Marino
			self::ST => 185, // São Tomé und Príncipe
			self::SA => 186, // Saudi-Arabien
			self::SE => 187, // Schweden
			self::SN => 188, // Senegal
			self::RS => 189, // Serbien
			self::SC => 190, // Seychellen
			self::SL => 191, // Sierra Leone
			self::ZW => 192, // Simbabwe
			self::SG => 193, // Singapur
			self::SX => 194, // Sint Maarten
			self::SK => 195, // Slowakei
			self::SI => 196, // Slowenien
			self::SO => 197, // Somalia
			self::HK => 198, // Sonderverwaltungsregion Hongkong
			self::MO => 199, // Sonderverwaltungsregion Macau
			self::ES => 200, // Spanien
			self::SJ => 201, // Spitzbergen und Jan Mayen
			self::LK => 202, // Sri Lanka
			self::BL => 203, // St. Barthélemy
			self::SH => 204, // St. Helena
			self::KN => 205, // St. Kitts und Nevis
			self::LC => 206, // St. Lucia
			self::MF => 207, // St. Martin
			self::PM => 208, // St. Pierre und Miquelon
			self::VC => 209, // St. Vincent und die Grenadinen
			self::ZA => 210, // Südafrika
			self::SD => 211, // Sudan
			self::GS => 212, // Südgeorgien und die Südlichen Sandwichinseln
			self::KR => 213, // Südkorea
			self::SS => 214, // Südsudan
			self::SR => 215, // Suriname
			self::SY => 216, // Syrien
			self::TJ => 217, // Tadschikistan
			self::TW => 218, // Taiwan
			self::TZ => 219, // Tansania
			self::TH => 220, // Thailand
			self::TL => 221, // Timor-Leste
			self::TG => 222, // Togo
			self::TK => 223, // Tokelau
			self::TO => 224, // Tonga
			self::TT => 225, // Trinidad und Tobago
			self::TD => 226, // Tschad
			self::CZ => 227, // Tschechien
			self::TN => 228, // Tunesien
			self::TR => 229, // Türkei
			self::TM => 230, // Turkmenistan
			self::TC => 231, // Turks- und Caicosinseln
			self::TV => 232, // Tuvalu
			self::UG => 233, // Uganda
			self::UA => 234, // Ukraine
			self::HU => 235, // Ungarn
			self::UY => 236, // Uruguay
			self::UZ => 237, // Usbekistan
			self::VU => 238, // Vanuatu
			self::VA => 239, // Vatikanstadt
			self::VE => 240, // Venezuela
			self::AE => 241, // Vereinigte Arabische Emirate
			self::US => 242, // Vereinigte Staaten
			self::GB => 243, // Vereinigtes Königreich
			self::VN => 244, // Vietnam
			self::WF => 245, // Wallis und Futuna
			self::CX => 246, // Weihnachtsinsel
			self::EH => 247, // Westsahara
			self::CF => 248, // Zentralafrikanische Republik
			self::CY => 249, // Zypern
		};
	}

	public function active(): bool
	{
		return true;
	}
}
